### ISSUE TITLE
module compiled with swift 3.1 cannot be imported in swift 3.0.2

### ISSUE THREAD

**Issue by Lithium-HD** [AzAli71/AZPersianCalendar#1]
سلام دوست عزیز
مرسی بابت زحمتی که کشیدی. من الان این خطا رو میگیرم و هر چی سرچ میزنم نمیتونم حلش کنم

نحوه اد کردنش به پروژه رو هم لطف کنی توضیح بدی ممنون میشم

**Comment by aliazadeh** [comment]
I think you need to upgrade your xcode , go to the app store and update your xcode version your issue will be fix the last xcode version is 8.3.2

**Comment by Lithium-HD** [comment]
well, It's not possible for me to upgrade xcode at the moment, I hoped you'd had a solution for this by putting this lib on cocoapods. anyway thank you for your time
