### ISSUE TITLE
AZCalendar Universal Builder ?

### ISSUE THREAD

**Issue by smtyldr** [AzAli71/AZPersianCalendar#2]
Hello there,
I am working on the simulator when I use AZ Calendar. But I get an error when I try to install the project on the iPhone. Can you correct ?

Thank you.

**Comment by aliazadeh** [comment]
@SmT6134  hi , project has updated now you can drag classes directory in SwiftSample directory  to your project and it should be works , test it and give me your feedback

**Comment by smtyldr** [comment]
Hi, I used the objective-c framework. Can you update it ?

Thank you.

**Comment by aliazadeh** [comment]
@SmT6134 Objective-C project has updated , it should works fine

**Comment by smtyldr** [comment]
Thank you. It works very well :)
